services:
  - type: web
    name: aula07-webhook-api
    runtime: python
    plan: free
    branch: main
    autoDeployTrigger: checksPass
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: WEBHOOK_TOKEN
        sync: false